In [6]:
import pandas as pd
import numpy as np
import requests
import time
import re
import glob
import os

pd.options.display.max_columns = 999

## Combine Historical Team Wins and Team Stats into one main dataframe `mdf`

In [2]:
def clean_team_name(my_string):
    if '*' in my_string:
        return my_string[:-5].strip()
    else:
        return my_string[:-4].strip()

In [3]:
def clean_team_name2(my_string):
    if '*' in my_string:
        return my_string[:-1].strip()
    else:
        return my_string.strip()

In [4]:
years = ['2022','2021', '2020', '2019', '2018','2017', '2016', '2015', '2014', '2013', '2012', '2011', 
         '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', 
         '1999', '1998', '1997', '1996', '1995', '1994', '1993', '1992', '1991', '1990',
        '1989', '1988', '1987', '1986', '1985', '1984', '1983', '1982', '1981', '1980']

for year in years:
    if year == '2022': 
        url = f'https://www.basketball-reference.com/leagues/NBA_{year}.html'
        res = requests.get(url)
        with open(f'./Data/html_files/NBA_{year}.xls', 'wb') as f:
            f.write(res.content)

        df = pd.read_html(f'./Data/html_files/NBA_{year}.xls')

        # get records 
        wins_df1 = pd.DataFrame(df[0]) 
        wins_df1.rename({'Eastern Conference': 'Team'}, axis = 1, inplace = True)
        wins_df1['Team'] = wins_df1['Team'].map(lambda x: clean_team_name(x))
        wins_df2 = pd.DataFrame(df[1]) 
        wins_df2.rename({'Western Conference': 'Team'}, axis = 1, inplace = True)
        wins_df2['Team'] = wins_df2['Team'].map(lambda x: clean_team_name(x))
        dfs = [wins_df1, wins_df2]
        wins_df = pd.concat(dfs, ignore_index = True)

        # get stats
        stats = pd.DataFrame(df[4]) 
        stats['Team'] = stats['Team'].map(lambda x: clean_team_name2(x))

        # merge and save to .csv
        df_merged = pd.merge(left = wins_df, right = stats, on = 'Team')
        df_merged['team_year'] = df_merged['Team'] + '_' + year
        df_merged['year'] = year
        df_merged.to_csv(f'./Data/yearly_stats/{year}_stats.csv')
        time.sleep(3)
    elif int(year) >2015 :
        url = f'https://www.basketball-reference.com/leagues/NBA_{year}.html'
        res = requests.get(url)
        with open(f'./Data/html_files/NBA_{year}.xls', 'wb') as f:
            f.write(res.content)

        df = pd.read_html(f'./Data/html_files/NBA_{year}.xls')

        # get records 
        wins_df1 = pd.DataFrame(df[0]) 
        wins_df1.rename({'Eastern Conference': 'Team'}, axis = 1, inplace = True)
        wins_df1['Team'] = wins_df1['Team'].map(lambda x: clean_team_name2(x))
        wins_df2 = pd.DataFrame(df[1]) 
        wins_df2.rename({'Western Conference': 'Team'}, axis = 1, inplace = True)
        wins_df2['Team'] = wins_df2['Team'].map(lambda x: clean_team_name2(x))
        dfs = [wins_df1, wins_df2]
        wins_df = pd.concat(dfs, ignore_index = True)

        # get stats
        stats = pd.DataFrame(df[4]) 
        stats['Team'] = stats['Team'].map(lambda x: clean_team_name2(x))

        # merge and save to .csv
        df_merged = pd.merge(left = wins_df, right = stats, on = 'Team')
        df_merged['team_year'] = df_merged['Team'] + '_' + year
        df_merged['year'] = year
        df_merged.to_csv(f'./Data/yearly_stats/{year}_stats.csv')
        time.sleep(3)
       
    else:
        print(f'scraping for {year}')
        url = f'https://www.basketball-reference.com/leagues/NBA_{year}.html'
        res = requests.get(url)
        with open(f'./Data/html_files/NBA_{year}.xls', 'wb') as f:
            f.write(res.content)

        df = pd.read_html(f'./Data/html_files/NBA_{year}.xls')

        # get records 
        wins_df1 = pd.DataFrame(df[0]) 
        wins_df1.rename({'Eastern Conference': 'Team'}, axis = 1, inplace = True)
        wins_df1['Team'] = wins_df1['Team'].map(lambda x: clean_team_name2(x))
        wins_df2 = pd.DataFrame(df[1]) 
        wins_df2.rename({'Western Conference': 'Team'}, axis = 1, inplace = True)
        wins_df2['Team'] = wins_df2['Team'].map(lambda x: clean_team_name2(x))
        dfs = [wins_df1, wins_df2]
        wins_df = pd.concat(dfs, ignore_index = True)

        # get stats
        stats = pd.DataFrame(df[3]) 
        stats['Team'] = stats['Team'].map(lambda x: clean_team_name2(x))

        # merge and save to .csv
        df_merged = pd.merge(left = wins_df, right = stats, on = 'Team')
        df_merged['team_year'] = df_merged['Team'] + '_' + year
        df_merged['year'] = year
        df_merged.to_csv(f'./Data/yearly_stats/{year}_stats.csv')
        time.sleep(3)

scraping for 2015
scraping for 2014
scraping for 2013
scraping for 2012
scraping for 2011
scraping for 2010
scraping for 2009
scraping for 2008
scraping for 2007
scraping for 2006
scraping for 2005
scraping for 2004
scraping for 2003
scraping for 2002
scraping for 2001
scraping for 2000
scraping for 1999
scraping for 1998
scraping for 1997
scraping for 1996
scraping for 1995
scraping for 1994
scraping for 1993
scraping for 1992
scraping for 1991
scraping for 1990
scraping for 1989
scraping for 1988
scraping for 1987
scraping for 1986
scraping for 1985
scraping for 1984
scraping for 1983
scraping for 1982
scraping for 1981
scraping for 1980

In [5]:
wins_df.shape, stats.shape

((26, 8), (23, 25))

In [6]:
stats

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1.0,Atlanta Hawks,82,241.2,38.3,83.8,0.458,0.6,2.2,0.251,37.8,81.6,0.463,24.4,31.9,0.765,15.4,28.5,43.9,21.4,8.3,6.8,20.2,26.5,101.6
1,2.0,Portland Trail Blazers,82,241.2,40.8,85.5,0.478,0.7,2.3,0.296,40.2,83.2,0.483,20.9,27.8,0.752,13.9,28.8,42.6,24.5,9.2,4.8,17.7,22.9,103.3
2,3.0,Seattle SuperSonics,82,241.8,41.6,90.5,0.459,0.7,2.9,0.246,40.8,87.6,0.466,20.0,26.2,0.764,14.7,29.4,44.0,24.6,8.9,4.8,18.5,24.4,103.8
3,4.0,Philadelphia 76ers,82,242.1,42.0,92.2,0.455,0.9,3.4,0.271,41.1,88.8,0.463,20.0,26.2,0.765,16.1,28.7,44.8,25.5,10.7,4.7,19.0,25.6,104.9
4,5.0,Kansas City Kings,82,241.5,40.6,85.3,0.476,0.5,2.1,0.238,40.1,83.2,0.482,23.2,30.5,0.763,13.9,32.2,46.1,21.7,8.5,5.2,21.5,25.3,104.9
5,6.0,Boston Celtics,82,242.4,41.9,89.2,0.470,0.9,3.2,0.286,41.0,86.0,0.477,20.9,27.1,0.770,14.2,28.0,42.2,22.8,8.4,5.1,19.9,25.1,105.7
6,7.0,Milwaukee Bucks,82,241.5,42.1,91.3,0.462,0.9,3.7,0.249,41.2,87.6,0.471,20.9,27.7,0.753,16.6,28.0,44.5,26.3,8.7,4.4,20.0,23.3,106.1
7,8.0,Phoenix Suns,82,240.9,43.5,91.2,0.476,1.2,3.6,0.337,42.2,87.6,0.482,19.4,25.8,0.752,14.8,29.8,44.7,24.7,10.8,4.7,20.3,25.0,107.5
8,9.0,Golden State Warriors,82,242.4,41.9,85.1,0.493,0.9,2.7,0.329,41.0,82.4,0.498,23.2,31.0,0.749,12.9,31.3,44.1,25.5,8.8,4.4,18.1,21.8,108.0
9,10.0,Utah Jazz,82,241.5,43.4,87.6,0.496,0.8,2.6,0.318,42.6,85.0,0.501,20.8,26.9,0.772,14.1,27.9,42.0,24.4,8.7,4.9,15.5,21.7,108.4
10,11.0,Los Angeles Lakers,82,242.4,45.4,96.6,0.470,1.0,3.3,0.285,44.5,93.3,0.477,17.4,23.0,0.759,16.0,27.3,43.3,28.3,9.7,4.7,17.3,22.7,109.2
11,12.0,New Jersey Nets,82,241.5,42.4,90.6,0.469,0.7,2.5,0.279,41.7,88.0,0.474,23.9,31.4,0.761,15.7,31.7,47.3,26.7,10.4,6.3,20.6,24.9,109.5
12,13.0,Washington Bullets,82,242.4,44.1,94.8,0.465,0.7,2.6,0.262,43.4,92.2,0.471,20.7,26.6,0.777,14.6,32.6,47.2,25.9,9.0,6.3,14.9,23.2,109.5
13,14.0,Chicago Bulls,82,242.7,43.7,88.1,0.496,0.7,2.4,0.271,43.1,85.6,0.503,22.1,28.8,0.768,14.1,28.6,42.7,25.7,10.3,6.1,18.8,26.9,110.2
14,15.0,Houston Rockets,82,243.0,44.6,90.0,0.496,0.7,2.6,0.270,43.9,87.4,0.502,20.7,26.3,0.788,15.7,28.3,44.0,27.1,9.5,5.2,19.5,25.0,110.6
15,16.0,San Diego Clippers,82,240.9,45.8,91.6,0.500,0.5,2.3,0.230,45.2,89.3,0.507,19.7,25.4,0.773,14.9,30.3,45.2,24.5,9.3,5.0,17.0,23.0,111.7
16,17.0,Indiana Pacers,82,242.1,45.0,92.0,0.489,0.7,2.8,0.246,44.4,89.2,0.497,21.1,28.0,0.756,17.0,31.1,48.1,28.3,9.0,5.7,21.4,24.7,111.9
17,18.0,Denver Nuggets,82,241.8,45.6,92.6,0.492,0.9,2.6,0.327,44.7,90.0,0.497,20.7,27.3,0.760,14.6,31.5,46.1,27.9,9.9,5.5,17.5,24.8,112.7
18,19.0,Cleveland Cavaliers,82,243.0,46.5,92.8,0.501,0.8,2.7,0.291,45.7,90.1,0.507,20.1,26.2,0.765,15.0,32.2,47.2,26.9,8.6,6.0,20.3,24.8,113.8
19,20.0,New York Knicks,82,241.2,45.2,91.4,0.495,0.7,2.4,0.278,44.5,89.0,0.501,24.0,31.2,0.770,15.8,29.7,45.4,26.1,9.9,4.8,20.7,24.9,115.1
20,21.0,Detroit Pistons,82,241.2,46.9,94.6,0.496,0.7,2.5,0.277,46.2,92.1,0.502,22.7,29.3,0.773,16.1,31.4,47.5,28.1,10.7,5.7,19.3,22.8,117.2
21,22.0,San Antonio Spurs,82,240.9,48.8,97.5,0.500,1.1,3.5,0.306,47.7,94.0,0.507,21.1,27.8,0.758,15.2,30.1,45.4,30.9,10.1,5.6,18.5,26.7,119.7
22,NaN,League Average,82,241.8,43.6,90.6,0.481,0.8,2.8,0.280,42.9,87.9,0.488,21.3,27.8,0.764,15.1,29.9,44.9,25.8,9.4,5.3,18.9,24.4,109.3

In [7]:
# check that both dfs have the team names in common.  should == 30
len(np.intersect1d(wins_df['Team'], stats['Team']))

22

In [8]:
path = 'Data/yearly_stats' # use your path
all_files = glob.glob(os.path.join(path, "*.csv"))
all_files

['Data/yearly_stats\\1980_stats.csv',
 'Data/yearly_stats\\1981_stats.csv',
 'Data/yearly_stats\\1982_stats.csv',
 'Data/yearly_stats\\1983_stats.csv',
 'Data/yearly_stats\\1984_stats.csv',
 'Data/yearly_stats\\1985_stats.csv',
 'Data/yearly_stats\\1986_stats.csv',
 'Data/yearly_stats\\1987_stats.csv',
 'Data/yearly_stats\\1988_stats.csv',
 'Data/yearly_stats\\1989_stats.csv',
 'Data/yearly_stats\\1990_stats.csv',
 'Data/yearly_stats\\1991_stats.csv',
 'Data/yearly_stats\\1992_stats.csv',
 'Data/yearly_stats\\1993_stats.csv',
 'Data/yearly_stats\\1994_stats.csv',
 'Data/yearly_stats\\1995_stats.csv',
 'Data/yearly_stats\\1996_stats.csv',
 'Data/yearly_stats\\1997_stats.csv',
 'Data/yearly_stats\\1998_stats.csv',
 'Data/yearly_stats\\1999_stats.csv',
 'Data/yearly_stats\\2000_stats.csv',
 'Data/yearly_stats\\2001_stats.csv',
 'Data/yearly_stats\\2002_stats.csv',
 'Data/yearly_stats\\2003_stats.csv',
 'Data/yearly_stats\\2004_stats.csv',
 'Data/yearly_stats\\2005_stats.csv',
 'Data/yearly_stats\\2006_stats.csv',
 'Data/yearly_stats\\2007_stats.csv',
 'Data/yearly_stats\\2008_stats.csv',
 'Data/yearly_stats\\2009_stats.csv',
 'Data/yearly_stats\\2010_stats.csv',
 'Data/yearly_stats\\2011_stats.csv',
 'Data/yearly_stats\\2012_stats.csv',
 'Data/yearly_stats\\2013_stats.csv',
 'Data/yearly_stats\\2014_stats.csv',
 'Data/yearly_stats\\2015_stats.csv',
 'Data/yearly_stats\\2016_stats.csv',
 'Data/yearly_stats\\2017_stats.csv',
 'Data/yearly_stats\\2018_stats.csv',
 'Data/yearly_stats\\2019_stats.csv',
 'Data/yearly_stats\\2020_stats.csv',
 'Data/yearly_stats\\2021_stats.csv',
 'Data/yearly_stats\\2022_stats.csv']

In [9]:
li = []
for file in all_files:
    df = pd.read_csv(file, index_col=None)
    li.append(df)

mdf = pd.concat(li, axis=0)
mdf.drop(columns = 'Unnamed: 0', inplace = True)
mdf.shape

(1194, 34)

In [10]:
mdf.head()

,Team,W,L,W/L%,GB,PS/G,PA/G,SRS,Rk,G,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,team_year,year
0,Boston Celtics,61,21,0.744,—,113.5,105.7,7.37,6.0,82,242.4,41.9,89.2,0.470,0.9,3.2,0.286,41.0,86.0,0.477,20.9,27.1,0.770,14.2,28.0,42.2,22.8,8.4,5.1,19.9,25.1,105.7,Boston Celtics_1980,1980
1,Philadelphia 76ers,59,23,0.720,2.0,109.1,104.9,4.04,4.0,82,242.1,42.0,92.2,0.455,0.9,3.4,0.271,41.1,88.8,0.463,20.0,26.2,0.765,16.1,28.7,44.8,25.5,10.7,4.7,19.0,25.6,104.9,Philadelphia 76ers_1980,1980
2,Washington Bullets,39,43,0.476,22.0,107.0,109.5,-2.27,13.0,82,242.4,44.1,94.8,0.465,0.7,2.6,0.262,43.4,92.2,0.471,20.7,26.6,0.777,14.6,32.6,47.2,25.9,9.0,6.3,14.9,23.2,109.5,Washington Bullets_1980,1980
3,New York Knicks,39,43,0.476,22.0,114.0,115.1,-0.96,20.0,82,241.2,45.2,91.4,0.495,0.7,2.4,0.278,44.5,89.0,0.501,24.0,31.2,0.770,15.8,29.7,45.4,26.1,9.9,4.8,20.7,24.9,115.1,New York Knicks_1980,1980
4,New Jersey Nets,34,48,0.415,27.0,108.3,109.5,-0.98,12.0,82,241.5,42.4,90.6,0.469,0.7,2.5,0.279,41.7,88.0,0.474,23.9,31.4,0.761,15.7,31.7,47.3,26.7,10.4,6.3,20.6,24.9,109.5,New Jersey Nets_1980,1980

In [12]:
mdf.to_csv('./Data/team_stats_1980_2022.csv')

## Scrape passing statistics from nba.com

In [1]:
url = 'https://stats.nba.com/stats/leaguedashptstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PerMode=PerGame&Period=0&PlayerExperience=&PlayerOrTeam=Team&PlayerPosition=&PtMeasureType=Passing&Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight='

In [4]:
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}

In [7]:
seasons = ['2021-22', '2020-21', '2019-20', '2018-19', '2017-18', '2016-17', '2015-16', '2014-15', '2013-14']
for season in seasons:
    url = f'https://stats.nba.com/stats/leaguedashptstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PerMode=PerGame&Period=0&PlayerExperience=&PlayerOrTeam=Team&PlayerPosition=&PtMeasureType=Passing&Season={season}&SeasonSegment=&SeasonType=Regular+Season&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight='
    res = requests.get(url=url, headers=headers).json()
    stats = res['resultSets'][0]['rowSet']
    df = pd.DataFrame(stats)
    df.rename(columns = {1: 'team_abbr',
                         2: 'team',
                         3: 'G',
                         4: 'W',
                         5: 'L',
                         7: 'passes_made',
                         9: 'asst',
                         11: 'secondary_asst',
                         12: 'potential_asst',
                         }, inplace = True)
    df.drop(columns = [0,6,8,10,13,14,15,16], inplace = True)
    df['year'] = season
    df.to_csv(f'./Data/nba_com_passing_stats/passing_{season}.csv')

In [8]:
path = 'Data/nba_com_passing_stats' # use your path
files = glob.glob(os.path.join(path, "*.csv"))

lst = []
for file in files:
    df = pd.read_csv(file, index_col=0)
    lst.append(df)

passing = pd.concat(lst, axis=0,)
passing

,team_abbr,team,G,W,L,passes_made,asst,secondary_asst,potential_asst,year
0,ATL,Atlanta Hawks,81,38,43,320.2,24.9,3.1,50.5,2013-14
1,BOS,Boston Celtics,82,25,57,297.9,21.0,2.4,45.6,2013-14
2,BKN,Brooklyn Nets,81,43,38,292.6,20.7,2.6,44.1,2013-14
3,CHA,Charlotte Bobcats,81,42,39,322.0,21.8,3.1,45.6,2013-14
4,CHI,Chicago Bulls,82,48,34,317.8,22.7,3.2,50.3,2013-14
...,...,...,...,...,...,...,...,...,...,...
25,SAC,Sacramento Kings,81,29,52,280.8,23.6,2.8,43.5,2021-22
26,SAS,San Antonio Spurs,82,34,48,288.8,27.9,3.0,51.5,2021-22
27,TOR,Toronto Raptors,82,48,34,281.1,22.1,3.0,44.3,2021-22
28,UTA,Utah Jazz,82,49,33,266.0,22.4,3.3,42.2,2021-22
29,WAS,Washington Wizards,82,35,47,289.3,25.0,2.8,45.5,2021-22

In [10]:
df.sort_values(by = 'passes_made', ascending = False)

,team_abbr,team,G,W,L,passes_made,asst,secondary_asst,potential_asst,year
7,DEN,Denver Nuggets,82,48,34,310.7,27.8,3.9,50.2,2021-22
9,GSW,Golden State Warriors,81,53,28,310.3,27.2,4.6,51.7,2021-22
11,IND,Indiana Pacers,82,25,57,308.3,25.4,2.9,47.4,2021-22
8,DET,Detroit Pistons,81,23,58,304.4,23.5,3.4,47.4,2021-22
3,CHA,Charlotte Hornets,81,43,38,301.5,28.1,3.7,50.8,2021-22
18,NOP,New Orleans Pelicans,81,35,46,300.3,25.0,3.2,48.0,2021-22
22,PHI,Philadelphia 76ers,82,51,31,299.5,23.7,3.5,42.2,2021-22
20,OKC,Oklahoma City Thunder,82,24,58,298.6,22.2,2.5,45.1,2021-22
5,CLE,Cleveland Cavaliers,82,44,38,297.0,25.2,3.5,48.8,2021-22
15,MIA,Miami Heat,82,53,29,295.7,25.5,3.5,49.2,2021-22
29,WAS,Washington Wizards,82,35,47,289.3,25.0,2.8,45.5,2021-22
1,BOS,Boston Celtics,81,51,30,289.0,24.9,4.0,45.9,2021-22
26,SAS,San Antonio Spurs,82,34,48,288.8,27.9,3.0,51.5,2021-22
21,ORL,Orlando Magic,82,22,60,284.0,23.7,2.2,47.4,2021-22
6,DAL,Dallas Mavericks,82,52,30,283.4,23.4,3.8,45.2,2021-22
27,TOR,Toronto Raptors,82,48,34,281.1,22.1,3.0,44.3,2021-22
13,LAL,Los Angeles Lakers,82,33,49,280.9,24.0,3.0,46.5,2021-22
17,MIN,Minnesota Timberwolves,82,46,36,280.9,25.7,3.4,48.5,2021-22
25,SAC,Sacramento Kings,81,29,52,280.8,23.6,2.8,43.5,2021-22
19,NYK,New York Knicks,81,36,45,279.0,21.9,2.5,41.2,2021-22
10,HOU,Houston Rockets,82,20,62,278.6,23.6,2.7,45.7,2021-22
24,POR,Portland Trail Blazers,82,27,55,276.9,22.9,3.0,46.0,2021-22
12,LAC,LA Clippers,81,42,39,276.8,24.1,3.7,43.9,2021-22
14,MEM,Memphis Grizzlies,81,55,26,274.2,25.9,3.2,46.9,2021-22
4,CHI,Chicago Bulls,82,46,36,269.5,23.9,3.6,44.3,2021-22
2,BKN,Brooklyn Nets,82,44,38,266.5,25.3,3.1,44.4,2021-22
28,UTA,Utah Jazz,82,49,33,266.0,22.4,3.3,42.2,2021-22
23,PHX,Phoenix Suns,81,63,18,258.8,27.4,3.5,50.2,2021-22
0,ATL,Atlanta Hawks,82,43,39,257.1,24.6,3.0,43.6,2021-22
16,MIL,Milwaukee Bucks,82,51,31,256.0,23.9,3.1,45.7,2021-22

In [11]:
passing.to_csv('./Data/team_passing_2013_2022.csv')

In [12]:
passing.to_excel('./Data/team_passing.xlsx',index=False)